#!/usr/bin/env bash
# Build Oriel Engine (CEF/Blink) artifacts for Mac:
#   - libcef_dll_wrapper.a
#   - Oriel Helper*.app bundles
#   - Vendor/CEF.xcconfig + build/oriel-engine/env.sh for xcodebuild
#
# Requires macOS + Xcode. Run after Scripts/fetch-cef-macos.sh (auto-fetches if missing).
set -euo pipefail

if [[ "$(uname -s)" != "Darwin" ]]; then
  echo "error: Oriel Engine build requires macOS" >&2
  exit 1
fi

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

DEST="${ORIEL_CEF_DIR:-$HOME/Library/Application Support/Oriel/CEF}"
VENDOR="$ROOT/Vendor/CEF"
OUT="${ORIEL_ENGINE_OUT:-$ROOT/build/oriel-engine}"
HELPER_SRC="$ROOT/Sources/CEF/Helper/process_helper_mac.cc"
XCCONFIG="$ROOT/Vendor/CEF.xcconfig"
ENTITLEMENTS="$ROOT/Resources/Oriel-macOS-Engine.entitlements"

arch_triple() {
  case "$(uname -m)" in
    arm64|aarch64) echo "arm64" ;;
    *) echo "x86_64" ;;
  esac
}
PROJECT_ARCH="${ORIEL_CEF_PROJECT_ARCH:-$(arch_triple)}"

if [[ ! -d "$DEST/Release/Chromium Embedded Framework.framework" ]]; then
  echo "CEF missing — fetching…"
  bash "$ROOT/Scripts/fetch-cef-macos.sh"
fi
if [[ ! -d "$DEST/libcef_dll" || ! -f "$DEST/CMakeLists.txt" ]]; then
  echo "error: CEF tree incomplete. Re-run Scripts/fetch-cef-macos.sh" >&2
  exit 1
fi
if [[ ! -f "$HELPER_SRC" ]]; then
  echo "error: missing $HELPER_SRC" >&2
  exit 1
fi

mkdir -p "$ROOT/Vendor" "$OUT/Frameworks"
rm -rf "$VENDOR"
ln -sfn "$DEST" "$VENDOR"

command -v cmake >/dev/null || { echo "error: cmake required (brew install cmake)" >&2; exit 1; }
command -v ninja >/dev/null || { echo "error: ninja required (brew install ninja)" >&2; exit 1; }

WRAPPER_BUILD="$DEST/build-wrapper"
echo "-> Building libcef_dll_wrapper ($PROJECT_ARCH)…"
rm -rf "$WRAPPER_BUILD"
mkdir -p "$WRAPPER_BUILD"
(
  cd "$WRAPPER_BUILD"
  cmake -G Ninja \
    -DPROJECT_ARCH="$PROJECT_ARCH" \
    -DCMAKE_BUILD_TYPE=Release \
    -DUSE_SANDBOX=OFF \
    "$DEST"
  ninja libcef_dll_wrapper
)

WRAPPER_A="$(find "$WRAPPER_BUILD" -name 'libcef_dll_wrapper.a' | head -1 || true)"
if [[ -z "$WRAPPER_A" || ! -f "$WRAPPER_A" ]]; then
  echo "error: libcef_dll_wrapper.a not found under $WRAPPER_BUILD" >&2
  exit 1
fi
cp -f "$WRAPPER_A" "$OUT/libcef_dll_wrapper.a"
WRAPPER_A="$OUT/libcef_dll_wrapper.a"

SDK_PATH="$(xcrun --sdk macosx --show-sdk-path)"
CXX="$(xcrun --sdk macosx --find clang++)"
MIN_VER="14.0"

build_helper() {
  local display_name="$1"   # e.g. "Oriel Helper (GPU)"
  local bundle_suffix="$2"  # e.g. ".gpu"
  local app_dir="$OUT/Frameworks/${display_name}.app"
  local macos_dir="$app_dir/Contents/MacOS"
  local plist="$app_dir/Contents/Info.plist"
  local bin_path="$macos_dir/${display_name}"

  rm -rf "$app_dir"
  mkdir -p "$macos_dir"

  echo "-> Compiling ${display_name}…"
  "$CXX" \
    -std=c++17 \
    -stdlib=libc++ \
    -mmacosx-version-min="$MIN_VER" \
    -arch "$PROJECT_ARCH" \
    -isysroot "$SDK_PATH" \
    -I"$DEST" \
    -O2 \
    "$HELPER_SRC" \
    "$WRAPPER_A" \
    -framework AppKit \
    -framework CoreFoundation \
    -framework ApplicationServices \
    -framework IOKit \
    -framework Security \
    -lc++ \
    -o "$bin_path"

  /usr/libexec/PlistBuddy -c "Clear dict" "$plist" 2>/dev/null || true
  cat > "$plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleDevelopmentRegion</key>
	<string>en</string>
	<key>CFBundleDisplayName</key>
	<string>${display_name}</string>
	<key>CFBundleExecutable</key>
	<string>${display_name}</string>
	<key>CFBundleIdentifier</key>
	<string>net.inveil.oriel.helper${bundle_suffix}</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>${display_name}</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>1.0.0</string>
	<key>CFBundleVersion</key>
	<string>1</string>
	<key>LSEnvironment</key>
	<dict>
		<key>MallocNanoZone</key>
		<string>0</string>
	</dict>
	<key>LSMinimumSystemVersion</key>
	<string>${MIN_VER}</string>
	<key>LSUIElement</key>
	<string>1</string>
	<key>NSSupportsAutomaticGraphicsSwitching</key>
	<true/>
</dict>
</plist>
PLIST

  codesign --force --sign - --entitlements "$ENTITLEMENTS" "$app_dir" 2>/dev/null \
    || codesign --force --sign - "$app_dir"
}

# CEF helper naming convention relative to main app "Oriel".
build_helper "Oriel Helper" ""
build_helper "Oriel Helper (Alerts)" ".alerts"
build_helper "Oriel Helper (GPU)" ".gpu"
build_helper "Oriel Helper (Plugin)" ".plugin"
build_helper "Oriel Helper (Renderer)" ".renderer"

# xcconfig for Xcode / xcodebuild — load CEF at runtime; link wrapper only.
cat > "$XCCONFIG" <<EOF
// Generated by Scripts/build-oriel-engine-macos.sh — do not commit.
SWIFT_ACTIVE_COMPILATION_CONDITIONS = \$(inherited) ORIEL_HAS_CEF
OTHER_SWIFT_FLAGS = \$(inherited) -DORIEL_HAS_CEF
OTHER_CFLAGS = \$(inherited) -DORIEL_HAS_CEF=1
OTHER_CPLUSPLUSFLAGS = \$(inherited) -DORIEL_HAS_CEF=1 -std=c++17
HEADER_SEARCH_PATHS = \$(inherited) \$(SRCROOT)/Vendor/CEF
LIBRARY_SEARCH_PATHS = \$(inherited) \$(SRCROOT)/build/oriel-engine
OTHER_LDFLAGS = \$(inherited) -lcef_dll_wrapper -lc++ -framework AppKit -framework CoreFoundation
LD_RUNPATH_SEARCH_PATHS = \$(inherited) @executable_path/../Frameworks @loader_path/../Frameworks
CLANG_CXX_LANGUAGE_STANDARD = c++17
EOF

cat > "$OUT/env.sh" <<EOF
# Sourced by Scripts/make-macos-dmg.sh
export ORIEL_ENGINE_READY=1
export ORIEL_ENGINE_ARCH=$PROJECT_ARCH
export ORIEL_ENGINE_WRAPPER="$WRAPPER_A"
export ORIEL_ENGINE_FRAMEWORKS="$OUT/Frameworks"
export ORIEL_ENGINE_CEF_FRAMEWORK="$DEST/Release/Chromium Embedded Framework.framework"
export ORIEL_ENGINE_XCCONFIG="$XCCONFIG"
export ORIEL_ENGINE_ENTITLEMENTS="$ENTITLEMENTS"
EOF

cat <<EOF
Oriel Engine build ready:
  wrapper:  $WRAPPER_A
  helpers:  $OUT/Frameworks/
  xcconfig: $XCCONFIG

Next: bash Scripts/make-macos-dmg.sh
EOF
